// Pricing PDF generators — used by Products "Today's Prices" tab and Pricing module.
// A4 Landscape, company letterhead, table of filtered products, footer with metadata.

import { drawLetterhead } from "@shared/pdf-letterhead";
import { ensureNotoSansRegistered } from "@/lib/pdf-fonts";
import logoAssetUrl from "@assets/HE-LOGO.jpeg";

async function loadJsPDF() {
  const mod = await import("jspdf");
  return mod.default || (mod as any).jsPDF;
}

async function loadLogoDataUrl(): Promise<string | undefined> {
  try {
    const res  = await fetch(logoAssetUrl);
    const blob = await res.blob();
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload  = () => resolve(reader.result as string);
      reader.onerror = reject;
      reader.readAsDataURL(blob);
    });
  } catch { return undefined; }
}

const C = {
  headerBg:   [30, 41, 59]    as [number, number, number],
  accent:     [59, 130, 246]  as [number, number, number],
  white:      [255, 255, 255] as [number, number, number],
  primary:    [15, 23, 42]    as [number, number, number],
  secondary:  [100, 116, 139] as [number, number, number],
  border:     [226, 232, 240] as [number, number, number],
  rowAlt:     [248, 250, 252] as [number, number, number],
  green:      [22, 163, 74]   as [number, number, number],
  amber:      [217, 119, 6]   as [number, number, number],
  red:        [220, 38, 38]   as [number, number, number],
};

function fmtINR(val: number | string | null | undefined): string {
  if (val === null || val === undefined || val === "") return "—";
  const n = Number(val);
  if (isNaN(n)) return "—";
  return `Rs.${n.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

function drawFooter(doc: any, pageWidth: number, margin: number, generatedOn: string, generatedBy: string) {
  const total = doc.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    const pageH = doc.internal.pageSize.getHeight();
    const y = pageH - 8;
    doc.setDrawColor(...C.border);
    doc.setLineWidth(0.2);
    doc.line(margin, y - 3, pageWidth - margin, y - 3);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.secondary);
    doc.text(`Generated On: ${generatedOn}`, margin, y);
    doc.text(`Generated By: ${generatedBy}`, pageWidth / 2, y, { align: "center" });
    doc.text(`Page ${i} of ${total}`, pageWidth - margin, y, { align: "right" });
  }
}

// ─── 1. Products Module — Today's Prices tab ──────────────────────────────────
export interface ProductsPriceRow {
  name: string;
  sku: string;
  unit: string;
  type: string;
  gridType: string;
  gstRate: string | number;
  effectivePrice: string | null;
  source: string;
  floorPrice: string | null;
  lastSoldPrice: string | null;
  lastSoldDate: string | null;
  status: string; // "Confirmed Today" | "Fallback" | "No Sheet" | "Confirmed" | "Partial" | "Missing"
}

export async function generateProductsPricePDF(
  rows: ProductsPriceRow[],
  filterLabel: string,
  generatedBy: string,
): Promise<Blob> {
  const JsPDF   = await loadJsPDF();
  const logoUrl = await loadLogoDataUrl();
  const doc     = new JsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  await ensureNotoSansRegistered(doc);

  const pageW  = doc.internal.pageSize.getWidth();  // 297mm
  const pageH  = doc.internal.pageSize.getHeight(); // 210mm
  const margin = 10;
  const generatedOn = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata", dateStyle: "medium", timeStyle: "short" });

  let y = drawLetterhead(doc, {
    pageWidth: pageW,
    margin,
    title: `TODAY'S PRICE LIST — ${filterLabel.toUpperCase()}`,
    logoDataUrl: logoUrl,
    bannerSubtitle: new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "2-digit", month: "short", year: "numeric" }),
  });

  y += 2;

  // Column definitions
  const cols = [
    { header: "Product",                  w: 58, align: "left"  as const },
    { header: "SKU",                      w: 24, align: "left"  as const },
    { header: "Unit",                     w: 12, align: "center"as const },
    { header: "Effective Price (Ex GST)", w: 30, align: "right" as const },
    { header: "Effective Price (Inc GST)",w: 30, align: "right" as const },
    { header: "Source",                   w: 20, align: "center"as const },
    { header: "Floor Price",              w: 24, align: "right" as const },
    { header: "Last Sold",                w: 24, align: "right" as const },
    { header: "Last Sold Date",           w: 22, align: "center"as const },
    { header: "Status",                   w: 21, align: "center"as const },
  ];
  const tableW = cols.reduce((s, c) => s + c.w, 0);
  const startX = margin;
  const rowH   = 7;
  const headerH = 8;

  const drawTableHeader = (yy: number) => {
    doc.setFillColor(...C.accent);
    doc.rect(startX, yy, tableW, headerH, "F");
    let x = startX;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...C.white);
    for (const col of cols) {
      const tx = col.align === "right" ? x + col.w - 2 : col.align === "center" ? x + col.w / 2 : x + 2;
      doc.text(col.header, tx, yy + 5.5, { align: col.align });
      x += col.w;
    }
    return yy + headerH;
  };

  y = drawTableHeader(y);

  doc.setFontSize(7);
  let rowIdx = 0;

  for (const row of rows) {
    if (y + rowH > pageH - 15) {
      doc.addPage();
      y = drawLetterhead(doc, { pageWidth: pageW, margin, title: `TODAY'S PRICE LIST — ${filterLabel.toUpperCase()}`, logoDataUrl: logoUrl, bannerSubtitle: new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "2-digit", month: "short", year: "numeric" }) });
      y += 2;
      y = drawTableHeader(y);
    }

    if (rowIdx % 2 === 1) {
      doc.setFillColor(...C.rowAlt);
      doc.rect(startX, y, tableW, rowH, "F");
    }

    doc.setDrawColor(...C.border);
    doc.setLineWidth(0.1);
    doc.line(startX, y + rowH, startX + tableW, y + rowH);

    const effIncGst = row.effectivePrice !== null
      ? Number(row.effectivePrice) * (1 + Number(row.gstRate ?? 0) / 100) : null;
    const values = [
      doc.splitTextToSize(row.name, cols[0].w - 3)[0],
      row.sku,
      row.unit,
      fmtINR(row.effectivePrice),
      fmtINR(effIncGst),
      row.source === "today" ? "Today" : row.source === "fallback" ? "Fallback" : row.source === "Confirmed" ? "Confirmed" : row.source === "Partial" ? "Partial" : "None",
      fmtINR(row.floorPrice),
      fmtINR(row.lastSoldPrice),
      row.lastSoldDate ? new Date(row.lastSoldDate).toLocaleDateString("en-IN", { day: "2-digit", month: "short" }) : "—",
      row.status,
    ];

    let x = startX;
    doc.setTextColor(...C.primary);
    doc.setFont("helvetica", "normal");
    for (let i = 0; i < cols.length; i++) {
      const col = cols[i];
      const tx  = col.align === "right" ? x + col.w - 2 : col.align === "center" ? x + col.w / 2 : x + 2;
      // Colour status column
      if (i === 8) {
        if (row.status === "Confirmed Today") doc.setTextColor(...C.green);
        else if (row.status === "Fallback") doc.setTextColor(...C.amber);
        else doc.setTextColor(...C.red);
      } else {
        doc.setTextColor(...C.primary);
      }
      doc.text(values[i], tx, y + 4.8, { align: col.align });
      x += col.w;
    }

    y += rowH;
    rowIdx++;
  }

  // Summary row
  doc.setFillColor(...C.headerBg);
  doc.rect(startX, y, tableW, rowH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...C.white);
  doc.text(`Total: ${rows.length} product${rows.length !== 1 ? "s" : ""}`, startX + 2, y + 4.8);

  drawFooter(doc, pageW, margin, generatedOn, generatedBy);
  return doc.output("blob");
}

// ─── 2. Pricing Module (/pricing page) ────────────────────────────────────────
export interface PricingModuleRow {
  name: string;
  sku: string;
  unit: string;
  gridType: string;
  gstRate: number;
  totalStock: number;
  supplierPrice: number | null;
  blendedCost: number | null;
  effectivePrice: number | null;
  marginPct: number | null;
  pressureLevel: string; // "Safe" | "Medium" | "High Risk" | "None"
  status: string; // "Confirmed" | "Pending" | "No Sheet"
}

export async function generatePricingModulePDF(
  rows: PricingModuleRow[],
  filterLabel: string,
  generatedBy: string,
): Promise<Blob> {
  const JsPDF   = await loadJsPDF();
  const logoUrl = await loadLogoDataUrl();
  const doc     = new JsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  await ensureNotoSansRegistered(doc);

  const pageW  = doc.internal.pageSize.getWidth();
  const pageH  = doc.internal.pageSize.getHeight();
  const margin = 10;
  const generatedOn = new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata", dateStyle: "medium", timeStyle: "short" });

  let y = drawLetterhead(doc, {
    pageWidth: pageW,
    margin,
    title: `PRICING SHEET — ${filterLabel.toUpperCase()}`,
    logoDataUrl: logoUrl,
    bannerSubtitle: new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "2-digit", month: "short", year: "numeric" }),
  });

  y += 2;

  const cols = [
    { header: "Product",                  w: 58, align: "left"  as const },
    { header: "SKU",                      w: 24, align: "left"  as const },
    { header: "Grid Type",                w: 18, align: "center"as const },
    { header: "Stock",                    w: 13, align: "right" as const },
    { header: "Supplier Price",           w: 26, align: "right" as const },
    { header: "Blended Cost",             w: 24, align: "right" as const },
    { header: "Eff. Price (Ex GST)",      w: 26, align: "right" as const },
    { header: "Eff. Price (Inc GST)",     w: 26, align: "right" as const },
    { header: "Margin %",                 w: 18, align: "right" as const },
    { header: "Pressure",                 w: 18, align: "center"as const },
    { header: "Status",                   w: 16, align: "center"as const },
  ];
  const tableW  = cols.reduce((s, c) => s + c.w, 0);
  const startX  = margin;
  const rowH    = 7;
  const headerH = 8;

  const gridLabel = (gt: string) => {
    if (gt === "on_grid")  return "On Grid";
    if (gt === "off_grid") return "Off Grid";
    if (gt === "hybrid")   return "Hybrid";
    return "Others";
  };

  const drawTableHeader = (yy: number) => {
    doc.setFillColor(...C.accent);
    doc.rect(startX, yy, tableW, headerH, "F");
    let x = startX;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...C.white);
    for (const col of cols) {
      const tx = col.align === "right" ? x + col.w - 2 : col.align === "center" ? x + col.w / 2 : x + 2;
      doc.text(col.header, tx, yy + 5.5, { align: col.align });
      x += col.w;
    }
    return yy + headerH;
  };

  y = drawTableHeader(y);
  doc.setFontSize(7);
  let rowIdx = 0;

  for (const row of rows) {
    if (y + rowH > pageH - 15) {
      doc.addPage();
      y = drawLetterhead(doc, { pageWidth: pageW, margin, title: `PRICING SHEET — ${filterLabel.toUpperCase()}`, logoDataUrl: logoUrl, bannerSubtitle: new Date().toLocaleDateString("en-IN", { timeZone: "Asia/Kolkata", day: "2-digit", month: "short", year: "numeric" }) });
      y += 2;
      y = drawTableHeader(y);
    }

    if (rowIdx % 2 === 1) {
      doc.setFillColor(...C.rowAlt);
      doc.rect(startX, y, tableW, rowH, "F");
    }
    doc.setDrawColor(...C.border);
    doc.setLineWidth(0.1);
    doc.line(startX, y + rowH, startX + tableW, y + rowH);

    const pressureColor = row.pressureLevel === "High Risk" ? C.red : row.pressureLevel === "Medium" ? C.amber : C.green;

    const effIncGstPricing = row.effectivePrice !== null
      ? row.effectivePrice * (1 + Number(row.gstRate ?? 0) / 100) : null;
    const values = [
      doc.splitTextToSize(row.name, cols[0].w - 3)[0],
      row.sku,
      gridLabel(row.gridType),
      String(row.totalStock),
      fmtINR(row.supplierPrice),
      fmtINR(row.blendedCost),
      fmtINR(row.effectivePrice),
      fmtINR(effIncGstPricing),
      row.marginPct !== null ? row.marginPct.toFixed(1) + "%" : "—",
      row.pressureLevel === "None" ? "—" : row.pressureLevel,
      row.status,
    ];

    let x = startX;
    for (let i = 0; i < cols.length; i++) {
      const col = cols[i];
      const tx  = col.align === "right" ? x + col.w - 2 : col.align === "center" ? x + col.w / 2 : x + 2;
      if (i === 8 && row.pressureLevel !== "None") doc.setTextColor(...pressureColor);
      else if (i === 9) {
        if (row.status === "Confirmed") doc.setTextColor(...C.green);
        else if (row.status === "Pending") doc.setTextColor(...C.amber);
        else doc.setTextColor(...C.red);
      } else {
        doc.setTextColor(...C.primary);
      }
      doc.setFont("helvetica", "normal");
      doc.text(values[i], tx, y + 4.8, { align: col.align });
      x += col.w;
    }

    y += rowH;
    rowIdx++;
  }

  // Summary row
  doc.setFillColor(...C.headerBg);
  doc.rect(startX, y, tableW, rowH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.setTextColor(...C.white);
  doc.text(`Total: ${rows.length} product${rows.length !== 1 ? "s" : ""}`, startX + 2, y + 4.8);

  drawFooter(doc, pageW, margin, generatedOn, generatedBy);
  return doc.output("blob");
}
