import jsPDF from "jspdf";
import { COMPANY } from "@shared/letterhead";

const C = {
  headerBg: [30, 41, 59] as [number, number, number],
  headerText: [255, 255, 255] as [number, number, number],
  subText: [180, 190, 210] as [number, number, number],
  textPrimary: [15, 23, 42] as [number, number, number],
  textMuted: [100, 116, 139] as [number, number, number],
  tableHeaderBg: [241, 245, 249] as [number, number, number],
  tableAltBg: [248, 250, 252] as [number, number, number],
  tableBorder: [226, 232, 240] as [number, number, number],
  summaryBg: [239, 246, 255] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  amber: [180, 83, 9] as [number, number, number],
  green: [4, 120, 87] as [number, number, number],
};

const M = 10;
const PW = 297;
const PH = 210;
const CW = PW - M * 2;
const RH = 6.5;
const THH = 5.5;

function fmtINR(v: number | null | undefined): string {
  if (v === null || v === undefined) return "\u2014";
  return "\u20b9" + v.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function todayStr() {
  return new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

function drawHeader(doc: jsPDF, title: string, subtitle: string): number {
  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, PW, 26, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...C.headerText);
  doc.text(COMPANY.shortName, M, 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.subText);
  doc.text(COMPANY.tagline, M, 17);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...C.headerText);
  doc.text(title, PW / 2, 11, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.subText);
  doc.text(subtitle, PW / 2, 17, { align: "center" });

  doc.setFontSize(7);
  doc.text(todayStr(), PW - M, 11, { align: "right" });
  doc.text("Generated by ITFI ERP", PW - M, 17, { align: "right" });

  return 29;
}

interface ColDef {
  header: string;
  width: number;
  align?: "left" | "right" | "center";
}

function drawTableHeaders(doc: jsPDF, cols: ColDef[], y: number): number {
  const tw = cols.reduce((s, c) => s + c.width, 0);
  doc.setFillColor(...C.tableHeaderBg);
  doc.rect(M, y, tw, THH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(5.8);
  doc.setTextColor(...C.textMuted);
  let x = M;
  for (const col of cols) {
    const a = col.align ?? "left";
    const tx = a === "right" ? x + col.width - 1 : a === "center" ? x + col.width / 2 : x + 1.5;
    doc.text(col.header.toUpperCase(), tx, y + THH - 1.5, { align: a });
    x += col.width;
  }
  return y + THH;
}

function drawTable(
  doc: jsPDF,
  cols: ColDef[],
  rows: (string | number | null)[][],
  startY: number,
  rowColorFn?: (i: number, row: (string | number | null)[]) => [number, number, number] | null
): number {
  let y = drawTableHeaders(doc, cols, startY);

  for (let i = 0; i < rows.length; i++) {
    if (y + RH > PH - 12) {
      addPageFooter(doc);
      doc.addPage("a4", "landscape");
      y = M;
      y = drawTableHeaders(doc, cols, y);
    }

    const customColor = rowColorFn ? rowColorFn(i, rows[i]) : null;
    if (customColor) {
      doc.setFillColor(...customColor);
      doc.rect(M, y, cols.reduce((s, c) => s + c.width, 0), RH, "F");
    } else if (i % 2 === 0) {
      doc.setFillColor(...C.tableAltBg);
      doc.rect(M, y, cols.reduce((s, c) => s + c.width, 0), RH, "F");
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.2);
    doc.setTextColor(...C.textPrimary);

    let x = M;
    for (let j = 0; j < cols.length; j++) {
      const col = cols[j];
      const val = rows[i][j];
      const text = val === null || val === undefined ? "\u2014" : String(val);
      const a = col.align ?? "left";
      const tx = a === "right" ? x + col.width - 1 : a === "center" ? x + col.width / 2 : x + 1.5;
      doc.text(text, tx, y + RH - 2, { align: a, maxWidth: col.width - 2 });
      x += col.width;
    }

    doc.setDrawColor(...C.tableBorder);
    doc.setLineWidth(0.1);
    doc.line(M, y + RH, M + cols.reduce((s, c) => s + c.width, 0), y + RH);
    y += RH;
  }
  return y;
}

function addPageFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    doc.text(`Page ${i} of ${pages}`, PW / 2, PH - 5, { align: "center" });
    doc.text("ITFI Group \u2014 Confidential", M, PH - 5);
    doc.text(new Date().toISOString().slice(0, 10), PW - M, PH - 5, { align: "right" });
  }
}

function drawSummaryBand(
  doc: jsPDF,
  items: { label: string; value: number; valueStr?: string; color?: [number, number, number] }[],
  y: number
): number {
  const bandH = 14;
  doc.setFillColor(...C.summaryBg);
  doc.rect(M, y, CW, bandH, "F");
  const cellW = CW / items.length;
  items.forEach((item, i) => {
    const cx = M + i * cellW;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    doc.text(item.label, cx + cellW / 2, y + 5, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...(item.color ?? C.textPrimary));
    doc.text(item.valueStr ?? fmtINR(item.value), cx + cellW / 2, y + 11, { align: "center" });
    if (i < items.length - 1) {
      doc.setDrawColor(...C.tableBorder);
      doc.setLineWidth(0.3);
      doc.line(cx + cellW, y + 2, cx + cellW, y + bandH - 2);
    }
  });
  return y + bandH + 3;
}

// ── AP Aging PDF ─────────────────────────────────────────────────────────────

export interface APAgingRowPDF {
  supplierName: string;
  invoiceNumber: string;
  poNumber: string | null;
  invoiceDate: string;
  dueDate: string | null;
  totalAmount: number;
  totalPaid: number;
  balance: number;
  daysOverdue: number;
  bucket: string;
  status: string;
}

export interface AgingSummaryPDF {
  current: number;
  days1_30: number;
  days31_60: number;
  days61_90: number;
  days90plus: number;
  totalOutstanding: number;
}

export function generateAPAgingPDF(rows: APAgingRowPDF[], summary: AgingSummaryPDF, filterDesc: string): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "AP Aging Report", filterDesc || "Accounts Payable Outstanding");

  y = drawSummaryBand(doc, [
    { label: "Total Outstanding", value: summary.totalOutstanding, color: C.red },
    { label: "Current", value: summary.current, color: C.green },
    { label: "1\u201330 Days", value: summary.days1_30, color: C.amber },
    { label: "31\u201360 Days", value: summary.days31_60, color: C.amber },
    { label: "61\u201390 Days", value: summary.days61_90, color: C.red },
    { label: "90+ Days", value: summary.days90plus, color: C.red },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Supplier", width: 40 },
    { header: "Invoice #", width: 27 },
    { header: "PO #", width: 23 },
    { header: "Invoice Date", width: 23 },
    { header: "Due Date", width: 22 },
    { header: "Total", width: 26, align: "right" },
    { header: "Paid", width: 25, align: "right" },
    { header: "Balance", width: 26, align: "right" },
    { header: "Days", width: 14, align: "right" },
    { header: "Bucket", width: 17, align: "center" },
    { header: "Status", width: 14, align: "center" },
  ];

  const tableRows = rows.map(r => [
    r.supplierName,
    r.invoiceNumber,
    r.poNumber ?? "\u2014",
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "",
    fmtINR(r.totalAmount),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
    r.bucket,
    r.status,
  ]);

  drawTable(doc, cols, tableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── AR Aging PDF ─────────────────────────────────────────────────────────────

export interface ARAgingRowPDF {
  customerName: string;
  customerType: string;
  customerGSTIN: string | null;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string | null;
  grandTotal: number;
  totalPaid: number;
  balance: number;
  daysOverdue: number;
  bucket: string;
  status: string;
}

export function generateARAgingPDF(rows: ARAgingRowPDF[], summary: AgingSummaryPDF, filterDesc: string): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "AR Aging Report", filterDesc || "Accounts Receivable Outstanding");

  y = drawSummaryBand(doc, [
    { label: "Total Outstanding", value: summary.totalOutstanding, color: C.red },
    { label: "Current", value: summary.current, color: C.green },
    { label: "1\u201330 Days", value: summary.days1_30, color: C.amber },
    { label: "31\u201360 Days", value: summary.days31_60, color: C.amber },
    { label: "61\u201390 Days", value: summary.days61_90, color: C.red },
    { label: "90+ Days", value: summary.days90plus, color: C.red },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Customer", width: 36 },
    { header: "Type", width: 13, align: "center" },
    { header: "GSTIN", width: 28 },
    { header: "Invoice #", width: 26 },
    { header: "Invoice Date", width: 22 },
    { header: "Due Date", width: 22 },
    { header: "Grand Total", width: 26, align: "right" },
    { header: "Paid", width: 24, align: "right" },
    { header: "Balance", width: 25, align: "right" },
    { header: "Days", width: 13, align: "right" },
    { header: "Bucket", width: 17, align: "center" },
    { header: "Status", width: 15, align: "center" },
  ];

  const tableRows = rows.map(r => [
    r.customerName,
    r.customerType ?? "\u2014",
    r.customerGSTIN ?? "\u2014",
    r.invoiceNumber,
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "\u2014",
    fmtINR(r.grandTotal),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
    r.bucket,
    r.status,
  ]);

  drawTable(doc, cols, tableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── Daily Pricing PDF ─────────────────────────────────────────────────────────

export interface PricingProductPDF {
  productName: string;
  sku: string;
  category: string;
  totalStock: number;
  unit: string;
  blendedCost: number | null;
  globalFloor: number | null;
  strictFloor: number | null;
  confirmedPrice: number;
  marginPct: number | null;
  minMarginPct: number;
  pressureLevel: string;
  source: "today" | "fallback" | "none";
  hasConfirmedToday: boolean;
  hasUnconfirmedSheet: boolean;
  hasConfirmedSheet: boolean;
  sellPriority: boolean;
}

export interface PortfolioPDF {
  totalInventoryCost: number;
  revenueAtConfirmedPrices: number;
  requiredRevenueAtMinMargin: number;
  portfolioMarginPct: number | null;
  portfolioStatus: "SAFE" | "AT RISK";
  productsAtRisk: number;
  productsWithoutPriceCount: number;
  productsSellPriority: number;
}

// ── Combined Tax Report PDF (AP Aging + AR Aging) ────────────────────────────

export function generateTaxReportPDF(
  apRows: APAgingRowPDF[],
  apSummary: AgingSummaryPDF,
  arRows: ARAgingRowPDF[],
  arSummary: AgingSummaryPDF
): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  // ── AP Aging section ──────────────────────────────────────────────────────
  let y = drawHeader(doc, "Tax Report — AP & AR Aging", "Combined GST Compliance & Aging Summary");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.textPrimary);
  doc.text("ACCOUNTS PAYABLE AGING", M, y + 4);
  y += 7;

  y = drawSummaryBand(doc, [
    { label: "AP Outstanding", value: apSummary.totalOutstanding, color: C.red },
    { label: "Current", value: apSummary.current, color: C.green },
    { label: "1\u201330 Days", value: apSummary.days1_30, color: C.amber },
    { label: "31\u201360 Days", value: apSummary.days31_60, color: C.amber },
    { label: "61\u201390 Days", value: apSummary.days61_90, color: C.red },
    { label: "90+ Days", value: apSummary.days90plus, color: C.red },
  ], y);

  const apCols: ColDef[] = [
    { header: "Supplier", width: 38 },
    { header: "Invoice #", width: 25 },
    { header: "PO #", width: 22 },
    { header: "Invoice Date", width: 22 },
    { header: "Due Date", width: 22 },
    { header: "Total", width: 25, align: "right" },
    { header: "Paid", width: 24, align: "right" },
    { header: "Balance", width: 25, align: "right" },
    { header: "Days", width: 14, align: "right" },
    { header: "Bucket", width: 20, align: "center" },
    { header: "Status", width: 20, align: "center" },
  ];

  const apTableRows = apRows.map(r => [
    r.supplierName,
    r.invoiceNumber,
    r.poNumber ?? "\u2014",
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "",
    fmtINR(r.totalAmount),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
    r.bucket,
    r.status,
  ]);

  y = drawTable(doc, apCols, apTableRows, y + 2);

  // ── AR Aging section ──────────────────────────────────────────────────────
  if (y + 40 > PH - 12) {
    addPageFooter(doc);
    doc.addPage("a4", "landscape");
    y = M;
  } else {
    y += 8;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.textPrimary);
  doc.text("ACCOUNTS RECEIVABLE AGING", M, y + 4);
  y += 7;

  y = drawSummaryBand(doc, [
    { label: "AR Outstanding", value: arSummary.totalOutstanding, color: C.red },
    { label: "Current", value: arSummary.current, color: C.green },
    { label: "1\u201330 Days", value: arSummary.days1_30, color: C.amber },
    { label: "31\u201360 Days", value: arSummary.days31_60, color: C.amber },
    { label: "61\u201390 Days", value: arSummary.days61_90, color: C.red },
    { label: "90+ Days", value: arSummary.days90plus, color: C.red },
  ], y);

  const arCols: ColDef[] = [
    { header: "Customer", width: 34 },
    { header: "Type", width: 13, align: "center" },
    { header: "GSTIN", width: 26 },
    { header: "Invoice #", width: 24 },
    { header: "Invoice Date", width: 22 },
    { header: "Due Date", width: 22 },
    { header: "Grand Total", width: 25, align: "right" },
    { header: "Paid", width: 23, align: "right" },
    { header: "Balance", width: 24, align: "right" },
    { header: "Days", width: 13, align: "right" },
    { header: "Bucket", width: 18, align: "center" },
    { header: "Status", width: 13, align: "center" },
  ];

  const arTableRows = arRows.map(r => [
    r.customerName,
    r.customerType ?? "\u2014",
    r.customerGSTIN ?? "\u2014",
    r.invoiceNumber,
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "\u2014",
    fmtINR(r.grandTotal),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
    r.bucket,
    r.status,
  ]);

  drawTable(doc, arCols, arTableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── Inventory Report PDF ──────────────────────────────────────────────────────

export interface ProductRowPDF {
  id: string;
  name: string;
  sku: string;
  category: string;
  unit: string;
  costPrice: string | null;
  unitPrice: string;
}

export function generateInventoryPDF(products: ProductRowPDF[], stockMap: Map<string, number>): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "Inventory Report", `${products.length} products — as of ${todayStr()}`);

  const totalCost = products.reduce((sum, p) => {
    const qty = stockMap.get(p.id) ?? 0;
    return sum + qty * Number(p.costPrice ?? 0);
  }, 0);
  const totalValue = products.reduce((sum, p) => {
    const qty = stockMap.get(p.id) ?? 0;
    return sum + qty * Number(p.unitPrice);
  }, 0);

  y = drawSummaryBand(doc, [
    { label: "Total Products", value: products.length, valueStr: String(products.length), color: C.textPrimary },
    { label: "Inventory Cost Value", value: totalCost, color: C.amber },
    { label: "Inventory List Value", value: totalValue, color: C.green },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Product", width: 52 },
    { header: "SKU", width: 30 },
    { header: "Category", width: 30 },
    { header: "Unit", width: 16, align: "center" },
    { header: "Total Stock", width: 24, align: "right" },
    { header: "Cost Price", width: 30, align: "right" },
    { header: "List Price", width: 30, align: "right" },
    { header: "Stock Value (Cost)", width: 35, align: "right" },
  ];

  const tableRows = products.map(p => {
    const qty = stockMap.get(p.id) ?? 0;
    const cost = Number(p.costPrice ?? 0);
    return [p.name, p.sku, p.category, p.unit, qty, fmtINR(cost), fmtINR(Number(p.unitPrice)), fmtINR(qty * cost)];
  });

  drawTable(doc, cols, tableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── Staff Report PDF ──────────────────────────────────────────────────────────

export interface EmployeeRowPDF {
  id: string;
  name: string;
  department: string;
  designation: string;
  role: string;
  isActive: boolean;
}

export function generateStaffPDF(employees: EmployeeRowPDF[]): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  const active = employees.filter(e => e.isActive).length;
  let y = drawHeader(doc, "Staff Report", `${employees.length} employees — ${active} active`);

  y = drawSummaryBand(doc, [
    { label: "Total Employees", value: employees.length, valueStr: String(employees.length), color: C.textPrimary },
    { label: "Active", value: active, valueStr: String(active), color: C.green },
    { label: "Inactive", value: employees.length - active, valueStr: String(employees.length - active), color: C.red },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Name", width: 55 },
    { header: "Employee ID", width: 30, align: "center" },
    { header: "Department", width: 40 },
    { header: "Designation", width: 50 },
    { header: "Role", width: 40 },
    { header: "Status", width: 22, align: "center" },
  ];

  const tableRows = employees.map(e => [
    e.name,
    e.id.slice(0, 8).toUpperCase(),
    e.department,
    e.designation,
    e.role,
    e.isActive ? "Active" : "Inactive",
  ]);

  drawTable(doc, cols, tableRows, y + 2, (_i, row) => {
    if (row[5] === "Inactive") return [255, 245, 245] as [number, number, number];
    return null;
  });
  addPageFooter(doc);
  return doc.output("blob");
}

// ── Sales Report PDF ──────────────────────────────────────────────────────────

export function generateSalesReportPDF(rows: ARAgingRowPDF[]): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "Sales Report", `${rows.length} invoices — as of ${todayStr()}`);

  const totalRevenue = rows.reduce((s, r) => s + r.grandTotal, 0);
  const totalCollected = rows.reduce((s, r) => s + r.totalPaid, 0);
  const totalBalance = rows.reduce((s, r) => s + r.balance, 0);

  y = drawSummaryBand(doc, [
    { label: "Total Invoiced", value: totalRevenue, color: C.textPrimary },
    { label: "Total Collected", value: totalCollected, color: C.green },
    { label: "Outstanding", value: totalBalance, color: C.red },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Invoice #", width: 30 },
    { header: "Customer", width: 40 },
    { header: "Type", width: 14, align: "center" },
    { header: "Invoice Date", width: 24 },
    { header: "Due Date", width: 24 },
    { header: "Grand Total", width: 28, align: "right" },
    { header: "Collected", width: 26, align: "right" },
    { header: "Balance", width: 26, align: "right" },
    { header: "Status", width: 22, align: "center" },
    { header: "Bucket", width: 20, align: "center" },
  ];

  const tableRows = rows.map(r => [
    r.invoiceNumber,
    r.customerName,
    r.customerType ?? "\u2014",
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "\u2014",
    fmtINR(r.grandTotal),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.status,
    r.bucket,
  ]);

  drawTable(doc, cols, tableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── Financial Report PDF (Revenue + Payables) ─────────────────────────────────

export function generateFinancialReportPDF(arRows: ARAgingRowPDF[], apRows: APAgingRowPDF[]): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });

  const totalRevenue = arRows.reduce((s, r) => s + r.grandTotal, 0);
  const totalCollected = arRows.reduce((s, r) => s + r.totalPaid, 0);
  const totalARBalance = arRows.reduce((s, r) => s + r.balance, 0);
  const totalExpenses = apRows.reduce((s, r) => s + r.totalAmount, 0);
  const totalAPPaid = apRows.reduce((s, r) => s + r.totalPaid, 0);
  const totalAPBalance = apRows.reduce((s, r) => s + r.balance, 0);

  // ── Revenue section ────────────────────────────────────────────────────────
  let y = drawHeader(doc, "Financial Report", "Revenue & Payables Overview");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.textPrimary);
  doc.text("REVENUE (ACCOUNTS RECEIVABLE)", M, y + 4);
  y += 7;

  y = drawSummaryBand(doc, [
    { label: "Total Invoiced", value: totalRevenue, color: C.green },
    { label: "Total Collected", value: totalCollected, color: C.green },
    { label: "Outstanding AR", value: totalARBalance, color: C.amber },
  ], y);

  const arCols: ColDef[] = [
    { header: "Invoice #", width: 28 },
    { header: "Customer", width: 40 },
    { header: "Type", width: 14, align: "center" },
    { header: "Invoice Date", width: 24 },
    { header: "Grand Total", width: 28, align: "right" },
    { header: "Collected", width: 26, align: "right" },
    { header: "Balance", width: 26, align: "right" },
    { header: "Status", width: 22, align: "center" },
    { header: "Bucket", width: 20, align: "center" },
    { header: "Days", width: 14, align: "right" },
  ];

  const arTableRows = arRows.map(r => [
    r.invoiceNumber, r.customerName, r.customerType ?? "\u2014",
    r.invoiceDate?.slice(0, 10) ?? "",
    fmtINR(r.grandTotal), fmtINR(r.totalPaid), fmtINR(r.balance),
    r.status, r.bucket, r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
  ]);

  y = drawTable(doc, arCols, arTableRows, y + 2);

  // ── Payables section ───────────────────────────────────────────────────────
  if (y + 50 > PH - 12) {
    addPageFooter(doc);
    doc.addPage("a4", "landscape");
    y = M;
  } else {
    y += 8;
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(...C.textPrimary);
  doc.text("PAYABLES (ACCOUNTS PAYABLE)", M, y + 4);
  y += 7;

  y = drawSummaryBand(doc, [
    { label: "Total Invoiced (AP)", value: totalExpenses, color: C.red },
    { label: "Total Paid (AP)", value: totalAPPaid, color: C.amber },
    { label: "Outstanding AP", value: totalAPBalance, color: C.red },
  ], y);

  const apCols: ColDef[] = [
    { header: "Invoice #", width: 28 },
    { header: "Supplier", width: 40 },
    { header: "PO #", width: 22 },
    { header: "Invoice Date", width: 24 },
    { header: "Total", width: 28, align: "right" },
    { header: "Paid", width: 26, align: "right" },
    { header: "Balance", width: 26, align: "right" },
    { header: "Status", width: 22, align: "center" },
    { header: "Bucket", width: 20, align: "center" },
    { header: "Days", width: 14, align: "right" },
  ];

  const apTableRows = apRows.map(r => [
    r.invoiceNumber, r.supplierName, r.poNumber ?? "\u2014",
    r.invoiceDate?.slice(0, 10) ?? "",
    fmtINR(r.totalAmount), fmtINR(r.totalPaid), fmtINR(r.balance),
    r.status, r.bucket, r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
  ]);

  drawTable(doc, apCols, apTableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

export function generatePricingPDF(products: PricingProductPDF[], portfolio: PortfolioPDF, filterDesc: string): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "Daily Pricing Report", filterDesc || "FIFO Pricing & Margin Summary");

  y = drawSummaryBand(doc, [
    { label: "Inventory Cost", value: portfolio.totalInventoryCost, color: C.textPrimary },
    { label: "Revenue @ Conf. Prices", value: portfolio.revenueAtConfirmedPrices, color: C.green },
    { label: "Required @ Min Margin", value: portfolio.requiredRevenueAtMinMargin, color: C.amber },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Product", width: 40 },
    { header: "SKU", width: 22 },
    { header: "Category", width: 24 },
    { header: "Stock", width: 18, align: "right" },
    { header: "Blended Cost", width: 25, align: "right" },
    { header: "Global Floor", width: 25, align: "right" },
    { header: "Strict Floor", width: 25, align: "right" },
    { header: "Eff. Price", width: 25, align: "right" },
    { header: "Margin %", width: 18, align: "right" },
    { header: "Risk", width: 18, align: "center" },
    { header: "Source", width: 18, align: "center" },
    { header: "Status", width: 19, align: "center" },
  ];

  const tableRows = products.map(p => [
    (p.sellPriority ? "\uD83D\uDD25 " : "") + p.productName,
    p.sku,
    p.category,
    `${p.totalStock.toLocaleString()} ${p.unit}`,
    p.blendedCost !== null ? fmtINR(p.blendedCost) : "\u2014",
    p.globalFloor !== null ? fmtINR(p.globalFloor) : "\u2014",
    p.strictFloor !== null ? fmtINR(p.strictFloor) : "\u2014",
    fmtINR(p.confirmedPrice),
    p.marginPct !== null ? `${p.marginPct.toFixed(1)}%` : "\u2014",
    p.pressureLevel,
    p.source === "today" ? "Today" : p.source === "fallback" ? "Fallback" : "No Price",
    p.hasConfirmedToday ? "Confirmed" : p.hasUnconfirmedSheet ? "Pending" : "No Sheet",
  ]);

  drawTable(doc, cols, tableRows, y + 2, (i, row) => {
    const pressure = products[i]?.pressureLevel;
    if (pressure === "High Risk") return [255, 245, 245] as [number, number, number];
    return null;
  });

  addPageFooter(doc);
  return doc.output("blob");
}

// ── Phase 4C T7 — P&L Statement PDF ──────────────────────────────────────────
export interface PLStatementPDFData {
  period: { from: string | null; to: string | null };
  revenue: {
    salesRevenue: number;
    salesReturns: number;
    netRevenue: number;
    salesInvoiceCount: number;
    creditNoteCount: number;
  };
  cogs: { purchases: number; label: string; caveat: string; supplierInvoiceCount: number };
  grossProfit: number;
  operatingExpenses: {
    byCategory: { categoryId: string | null; categoryName: string; total: number }[];
    total: number;
    expenseCount: number;
  };
  netProfitBeforeTax: number;
  trend?: { month: string; revenue: number; expense: number; netProfit: number }[];
  trendWindow?: { from: string; to: string };
  notes: string[];
}

export interface PLChartImages {
  /** JPEG/PNG dataURL of the trend bar chart, captured from the on-screen Recharts SVG */
  trendImage?: { dataUrl: string; cssWidth: number; cssHeight: number; format: "PNG" | "JPEG" };
  /** JPEG/PNG dataURL of the expense breakdown donut */
  expenseImage?: { dataUrl: string; cssWidth: number; cssHeight: number; format: "PNG" | "JPEG" };
}

export function generatePLStatementPDF(d: PLStatementPDFData, charts: PLChartImages = {}): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pwP = 210, mP = 12;
  const periodStr = `Period: ${d.period.from ?? "—"} → ${d.period.to ?? "Today"}`;

  // Header band (portrait variant)
  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pwP, 24, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...C.headerText);
  doc.text(COMPANY.shortName, mP, 10);
  doc.setFontSize(11);
  doc.text("Profit & Loss Statement", pwP / 2, 10, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.subText);
  doc.text(COMPANY.tagline, mP, 16);
  doc.text(periodStr, pwP / 2, 16, { align: "center" });
  doc.text(todayStr(), pwP - mP, 10, { align: "right" });
  doc.text("Generated by ITFI ERP", pwP - mP, 16, { align: "right" });

  let y = 30;

  // Caveat banner
  doc.setFillColor(255, 251, 235);
  doc.setDrawColor(245, 158, 11);
  doc.setLineWidth(0.4);
  doc.roundedRect(mP, y, pwP - mP * 2, 14, 1, 1, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7.5);
  doc.setTextColor(120, 53, 15);
  doc.text(d.cogs.label + ":", mP + 3, y + 4.5);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(6.8);
  const caveatLines = doc.splitTextToSize(d.cogs.caveat, pwP - mP * 2 - 6);
  doc.text(caveatLines, mP + 3, y + 8);
  y += 17;

  // Statement table — 2 cols: Label | Amount
  const drawRow = (label: string, amount: number | null, opts: { bold?: boolean; indent?: number; topBorder?: boolean; muted?: boolean; bg?: [number, number, number] } = {}) => {
    const rh = 6;
    if (opts.bg) {
      doc.setFillColor(...opts.bg);
      doc.rect(mP, y, pwP - mP * 2, rh, "F");
    }
    if (opts.topBorder) {
      doc.setDrawColor(...C.tableBorder);
      doc.setLineWidth(0.3);
      doc.line(mP, y, pwP - mP, y);
    }
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.bold ? 9 : 8);
    doc.setTextColor(...(opts.muted ? C.textMuted : C.textPrimary));
    doc.text(label, mP + 2 + (opts.indent ?? 0), y + 4);
    if (amount !== null) {
      doc.text(fmtINR(amount), pwP - mP - 2, y + 4, { align: "right" });
    }
    y += rh;
  };

  drawRow("REVENUE", null, { bold: true, bg: C.tableHeaderBg });
  drawRow(`Sales Revenue (ex-GST) — ${d.revenue.salesInvoiceCount} invoices`, d.revenue.salesRevenue, { indent: 3 });
  drawRow(`Less: Sales Returns — ${d.revenue.creditNoteCount} CN`, -d.revenue.salesReturns, { indent: 3, muted: true });
  drawRow("Net Revenue", d.revenue.netRevenue, { bold: true, indent: 3, topBorder: true });
  y += 1;

  drawRow(d.cogs.label.toUpperCase(), null, { bold: true, bg: C.tableHeaderBg });
  drawRow(`Purchases — ${d.cogs.supplierInvoiceCount} supplier invoices`, -d.cogs.purchases, { indent: 3 });
  y += 1;

  drawRow("GROSS PROFIT", d.grossProfit, { bold: true, bg: C.summaryBg, topBorder: true });
  y += 1;

  drawRow("OPERATING EXPENSES", null, { bold: true, bg: C.tableHeaderBg });
  if (d.operatingExpenses.byCategory.length === 0) {
    drawRow("(no expenses in period)", null, { indent: 3, muted: true });
  } else {
    d.operatingExpenses.byCategory.forEach((c) => drawRow(c.categoryName, -c.total, { indent: 3 }));
  }
  drawRow("Total Operating Expenses", -d.operatingExpenses.total, { bold: true, indent: 3, topBorder: true });
  y += 2;

  // Net Profit highlight
  const positive = d.netProfitBeforeTax >= 0;
  doc.setFillColor(...(positive ? [240, 253, 244] : [254, 242, 242] as [number, number, number]));
  doc.setDrawColor(...(positive ? C.green : C.red));
  doc.setLineWidth(0.5);
  doc.rect(mP, y, pwP - mP * 2, 10, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...(positive ? C.green : C.red));
  doc.text("NET PROFIT BEFORE TAX", mP + 3, y + 6.5);
  doc.text(fmtINR(d.netProfitBeforeTax), pwP - mP - 3, y + 6.5, { align: "right" });
  y += 14;

  // Notes
  if (d.notes.length > 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    d.notes.forEach((n) => {
      const lines = doc.splitTextToSize("- " + n, pwP - mP * 2);
      doc.text(lines, mP, y);
      y += lines.length * 3;
    });
  }

  // ── Charts page (only if at least one chart image was supplied) ───────────
  if (charts.trendImage || charts.expenseImage) {
    doc.addPage();
    // Re-draw header band (consistent with page 1)
    doc.setFillColor(...C.headerBg);
    doc.rect(0, 0, pwP, 24, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...C.headerText);
    doc.text(COMPANY.shortName, mP, 10);
    doc.setFontSize(11);
    doc.text("P&L Visual Summary", pwP / 2, 10, { align: "center" });
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...C.subText);
    doc.text(periodStr, pwP / 2, 16, { align: "center" });
    doc.text(todayStr(), pwP - mP, 10, { align: "right" });

    let cy = 30;
    if (charts.trendImage) {
      const ti = charts.trendImage;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...C.textPrimary);
      doc.text("12-Month Revenue / Expense / Net Profit Trend", mP, cy);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(7);
      doc.setTextColor(...C.textMuted);
      const annot = d.trendWindow
        ? `Trend: 12 months ending ${d.trendWindow.to}  (decoupled from period filter)`
        : "Trend: last 12 months";
      doc.text(annot, mP, cy + 4);
      cy += 7;
      const w = pwP - mP * 2;
      const h = (ti.cssHeight / ti.cssWidth) * w;
      doc.addImage(ti.dataUrl, ti.format, mP, cy, w, h);
      cy += h + 8;
    }
    if (charts.expenseImage) {
      const ei = charts.expenseImage;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.setTextColor(...C.textPrimary);
      doc.text("Operating Expenses by Category", mP, cy);
      cy += 4;
      // Donut: render at half-width centred
      const w = (pwP - mP * 2) * 0.6;
      const h = (ei.cssHeight / ei.cssWidth) * w;
      const x = (pwP - w) / 2;
      doc.addImage(ei.dataUrl, ei.format, x, cy, w, h);
    }
  }

  addPageFooter(doc);
  return doc.output("blob");
}

// ── Phase 4C T8 — Cash Flow Statement PDF ────────────────────────────────────
export interface CashFlowStatementPDFData {
  period: { from: string | null; to: string | null };
  operating: {
    customerPaymentsReceived: number;
    supplierPaymentsMade: number;
    operatingExpenses: number;
    netOperating: number;
  };
  internal: {
    transfersGross: number;
    transfersNet: number;
    adjustments: { byReason: { reason: string; amount: number }[]; net: number };
    netInternal: number;
  };
  netChangeInCash: number;
  perAccount: {
    accountId: string;
    accountName: string;
    accountType: "bank" | "cash";
    opening: number;
    inflows: number;
    outflows: number;
    closing: number;
    netChange: number;
  }[];
  totals: { opening: number; inflows: number; outflows: number; closing: number; netChange: number };
  notes: { legacyReceiptsExcluded: { count: number; amount: number }; info: string[] };
}

export function generateCashFlowStatementPDF(d: CashFlowStatementPDFData): Blob {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pwP = 210, mP = 12;
  const periodStr = `Period: ${d.period.from ?? "—"} → ${d.period.to ?? "Today"}`;

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pwP, 24, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...C.headerText);
  doc.text(COMPANY.shortName, mP, 10);
  doc.setFontSize(11);
  doc.text("Cash Flow Statement (Direct Method)", pwP / 2, 10, { align: "center" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.subText);
  doc.text(COMPANY.tagline, mP, 16);
  doc.text(periodStr, pwP / 2, 16, { align: "center" });
  doc.text(todayStr(), pwP - mP, 10, { align: "right" });
  doc.text("Generated by ITFI ERP", pwP - mP, 16, { align: "right" });

  let y = 30;

  // Legacy receipts warning
  if (d.notes.legacyReceiptsExcluded.count > 0) {
    doc.setFillColor(255, 251, 235);
    doc.setDrawColor(245, 158, 11);
    doc.setLineWidth(0.4);
    doc.roundedRect(mP, y, pwP - mP * 2, 11, 1, 1, "FD");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(120, 53, 15);
    doc.text(`⚠ ${d.notes.legacyReceiptsExcluded.count} legacy receipt(s) ${fmtINR(d.notes.legacyReceiptsExcluded.amount)} excluded`, mP + 3, y + 4.5);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.text("Recorded against deprecated payments table without account attribution.", mP + 3, y + 8);
    y += 14;
  }

  const drawRow = (label: string, amount: number | null, opts: { bold?: boolean; indent?: number; topBorder?: boolean; bg?: [number, number, number]; muted?: boolean } = {}) => {
    const rh = 6;
    if (opts.bg) {
      doc.setFillColor(...opts.bg);
      doc.rect(mP, y, pwP - mP * 2, rh, "F");
    }
    if (opts.topBorder) {
      doc.setDrawColor(...C.tableBorder);
      doc.setLineWidth(0.3);
      doc.line(mP, y, pwP - mP, y);
    }
    doc.setFont("helvetica", opts.bold ? "bold" : "normal");
    doc.setFontSize(opts.bold ? 9 : 8);
    doc.setTextColor(...(opts.muted ? C.textMuted : C.textPrimary));
    doc.text(label, mP + 2 + (opts.indent ?? 0), y + 4);
    if (amount !== null) doc.text(fmtINR(amount), pwP - mP - 2, y + 4, { align: "right" });
    y += rh;
  };

  drawRow("OPERATING ACTIVITIES", null, { bold: true, bg: C.tableHeaderBg });
  drawRow("Customer Payments Received", d.operating.customerPaymentsReceived, { indent: 3 });
  drawRow("Supplier Payments Made", -d.operating.supplierPaymentsMade, { indent: 3 });
  drawRow("Operating Expenses", -d.operating.operatingExpenses, { indent: 3 });
  drawRow("Net Operating Cash Flow", d.operating.netOperating, { bold: true, indent: 3, topBorder: true });
  y += 1;

  drawRow("INTERNAL MOVEMENTS", null, { bold: true, bg: C.tableHeaderBg });
  drawRow(`Transfers (gross ${fmtINR(d.internal.transfersGross)} both legs — net ₹0)`, d.internal.transfersNet, { indent: 3, muted: true });
  if (d.internal.adjustments.byReason.length === 0) {
    drawRow("(no balance adjustments in period)", null, { indent: 3, muted: true });
  } else {
    d.internal.adjustments.byReason.forEach((a) => drawRow(`Adjustment: ${a.reason}`, a.amount, { indent: 3 }));
  }
  drawRow("Net Internal Movement", d.internal.netInternal, { bold: true, indent: 3, topBorder: true });
  y += 2;

  // Net Change highlight
  const positive = d.netChangeInCash >= 0;
  doc.setFillColor(...(positive ? [240, 253, 244] : [254, 242, 242] as [number, number, number]));
  doc.setDrawColor(...(positive ? C.green : C.red));
  doc.setLineWidth(0.5);
  doc.rect(mP, y, pwP - mP * 2, 10, "FD");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...(positive ? C.green : C.red));
  doc.text("NET CHANGE IN CASH", mP + 3, y + 6.5);
  doc.text(fmtINR(d.netChangeInCash), pwP - mP - 3, y + 6.5, { align: "right" });
  y += 14;

  // Per-Account Reconciliation — landscape-style table fits in portrait via narrower cols
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(...C.textPrimary);
  doc.text("Per-Account Reconciliation", mP, y);
  y += 4;

  const cols: { header: string; w: number; align?: "left" | "right" }[] = [
    { header: "Account", w: 50 },
    { header: "Opening", w: 27, align: "right" },
    { header: "Inflows", w: 27, align: "right" },
    { header: "Outflows", w: 27, align: "right" },
    { header: "Closing", w: 27, align: "right" },
    { header: "Δ", w: 28, align: "right" },
  ];
  // header
  doc.setFillColor(...C.tableHeaderBg);
  doc.rect(mP, y, pwP - mP * 2, 5.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(6.5);
  doc.setTextColor(...C.textMuted);
  let cx = mP;
  cols.forEach((c) => {
    const tx = c.align === "right" ? cx + c.w - 1 : cx + 1.5;
    doc.text(c.header.toUpperCase(), tx, y + 4, { align: c.align ?? "left" });
    cx += c.w;
  });
  y += 5.5;
  // rows (with page-break for many accounts; A4 portrait page height ≈ 297mm)
  const drawAcctHeader = () => {
    doc.setFillColor(...C.tableHeaderBg);
    doc.rect(mP, y, pwP - mP * 2, 5.5, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    let hx = mP;
    cols.forEach((c) => {
      const tx = c.align === "right" ? hx + c.w - 1 : hx + 1.5;
      doc.text(c.header.toUpperCase(), tx, y + 4, { align: c.align ?? "left" });
      hx += c.w;
    });
    y += 5.5;
  };

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(...C.textPrimary);
  d.perAccount.forEach((a, i) => {
    if (y + 5.5 > 285) { // bottom margin reserve for footer
      addPageFooter(doc);
      doc.addPage("a4", "portrait");
      y = 14;
      drawAcctHeader();
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...C.textPrimary);
    }
    if (i % 2 === 0) {
      doc.setFillColor(...C.tableAltBg);
      doc.rect(mP, y, pwP - mP * 2, 5.5, "F");
    }
    cx = mP;
    const cells = [
      `${a.accountName} (${a.accountType})`,
      fmtINR(a.opening),
      fmtINR(a.inflows),
      fmtINR(a.outflows),
      fmtINR(a.closing),
      fmtINR(a.netChange),
    ];
    cells.forEach((v, j) => {
      const c = cols[j];
      const tx = c.align === "right" ? cx + c.w - 1 : cx + 1.5;
      doc.text(v, tx, y + 4, { align: c.align ?? "left" });
      cx += c.w;
    });
    y += 5.5;
  });
  // Reserve space for total row + notes; new page if too close to bottom
  if (y + 12 > 285) {
    addPageFooter(doc);
    doc.addPage("a4", "portrait");
    y = 14;
  }
  // total row
  doc.setFillColor(...C.summaryBg);
  doc.rect(mP, y, pwP - mP * 2, 5.5, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  cx = mP;
  const totalCells = [
    "TOTAL",
    fmtINR(d.totals.opening),
    fmtINR(d.totals.inflows),
    fmtINR(d.totals.outflows),
    fmtINR(d.totals.closing),
    fmtINR(d.totals.netChange),
  ];
  totalCells.forEach((v, j) => {
    const c = cols[j];
    const tx = c.align === "right" ? cx + c.w - 1 : cx + 1.5;
    doc.text(v, tx, y + 4, { align: c.align ?? "left" });
    cx += c.w;
  });
  y += 8;

  // Notes
  if (d.notes.info.length > 0) {
    doc.setFont("helvetica", "italic");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    d.notes.info.forEach((n) => {
      const lines = doc.splitTextToSize("• " + n, pwP - mP * 2);
      doc.text(lines, mP, y);
      y += lines.length * 3;
    });
  }

  addPageFooter(doc);
  return doc.output("blob");
}
