import jsPDF from "jspdf";

const C = {
  headerBg: [30, 41, 59] as [number, number, number],
  headerText: [255, 255, 255] as [number, number, number],
  subText: [180, 190, 210] as [number, number, number],
  textPrimary: [15, 23, 42] as [number, number, number],
  textMuted: [100, 116, 139] as [number, number, number],
  tableHeaderBg: [241, 245, 249] as [number, number, number],
  tableAltBg: [248, 250, 252] as [number, number, number],
  tableBorder: [226, 232, 240] as [number, number, number],
  summaryBg: [239, 246, 255] as [number, number, number],
  red: [220, 38, 38] as [number, number, number],
  amber: [180, 83, 9] as [number, number, number],
  green: [4, 120, 87] as [number, number, number],
};

const M = 10;
const PW = 297;
const PH = 210;
const CW = PW - M * 2;
const RH = 6.5;
const THH = 5.5;

function fmtINR(v: number | null | undefined): string {
  if (v === null || v === undefined) return "\u2014";
  return "\u20b9" + v.toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

function todayStr() {
  return new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

function drawHeader(doc: jsPDF, title: string, subtitle: string): number {
  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, PW, 26, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...C.headerText);
  doc.text("ITFI Group", M, 11);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.subText);
  doc.text("Enterprise Resource Planning", M, 17);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...C.headerText);
  doc.text(title, PW / 2, 11, { align: "center" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(7.5);
  doc.setTextColor(...C.subText);
  doc.text(subtitle, PW / 2, 17, { align: "center" });

  doc.setFontSize(7);
  doc.text(todayStr(), PW - M, 11, { align: "right" });
  doc.text("Generated by ITFI ERP", PW - M, 17, { align: "right" });

  return 29;
}

interface ColDef {
  header: string;
  width: number;
  align?: "left" | "right" | "center";
}

function drawTableHeaders(doc: jsPDF, cols: ColDef[], y: number): number {
  const tw = cols.reduce((s, c) => s + c.width, 0);
  doc.setFillColor(...C.tableHeaderBg);
  doc.rect(M, y, tw, THH, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(5.8);
  doc.setTextColor(...C.textMuted);
  let x = M;
  for (const col of cols) {
    const a = col.align ?? "left";
    const tx = a === "right" ? x + col.width - 1 : a === "center" ? x + col.width / 2 : x + 1.5;
    doc.text(col.header.toUpperCase(), tx, y + THH - 1.5, { align: a });
    x += col.width;
  }
  return y + THH;
}

function drawTable(
  doc: jsPDF,
  cols: ColDef[],
  rows: (string | number | null)[][],
  startY: number,
  rowColorFn?: (i: number, row: (string | number | null)[]) => [number, number, number] | null
): number {
  let y = drawTableHeaders(doc, cols, startY);

  for (let i = 0; i < rows.length; i++) {
    if (y + RH > PH - 12) {
      addPageFooter(doc);
      doc.addPage("a4", "landscape");
      y = M;
      y = drawTableHeaders(doc, cols, y);
    }

    const customColor = rowColorFn ? rowColorFn(i, rows[i]) : null;
    if (customColor) {
      doc.setFillColor(...customColor);
      doc.rect(M, y, cols.reduce((s, c) => s + c.width, 0), RH, "F");
    } else if (i % 2 === 0) {
      doc.setFillColor(...C.tableAltBg);
      doc.rect(M, y, cols.reduce((s, c) => s + c.width, 0), RH, "F");
    }

    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.2);
    doc.setTextColor(...C.textPrimary);

    let x = M;
    for (let j = 0; j < cols.length; j++) {
      const col = cols[j];
      const val = rows[i][j];
      const text = val === null || val === undefined ? "\u2014" : String(val);
      const a = col.align ?? "left";
      const tx = a === "right" ? x + col.width - 1 : a === "center" ? x + col.width / 2 : x + 1.5;
      doc.text(text, tx, y + RH - 2, { align: a, maxWidth: col.width - 2 });
      x += col.width;
    }

    doc.setDrawColor(...C.tableBorder);
    doc.setLineWidth(0.1);
    doc.line(M, y + RH, M + cols.reduce((s, c) => s + c.width, 0), y + RH);
    y += RH;
  }
  return y;
}

function addPageFooter(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    doc.text(`Page ${i} of ${pages}`, PW / 2, PH - 5, { align: "center" });
    doc.text("ITFI Group \u2014 Confidential", M, PH - 5);
    doc.text(new Date().toISOString().slice(0, 10), PW - M, PH - 5, { align: "right" });
  }
}

function drawSummaryBand(
  doc: jsPDF,
  items: { label: string; value: number; color?: [number, number, number] }[],
  y: number
): number {
  const bandH = 14;
  doc.setFillColor(...C.summaryBg);
  doc.rect(M, y, CW, bandH, "F");
  const cellW = CW / items.length;
  items.forEach((item, i) => {
    const cx = M + i * cellW;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(6.5);
    doc.setTextColor(...C.textMuted);
    doc.text(item.label, cx + cellW / 2, y + 5, { align: "center" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...(item.color ?? C.textPrimary));
    doc.text(fmtINR(item.value), cx + cellW / 2, y + 11, { align: "center" });
    if (i < items.length - 1) {
      doc.setDrawColor(...C.tableBorder);
      doc.setLineWidth(0.3);
      doc.line(cx + cellW, y + 2, cx + cellW, y + bandH - 2);
    }
  });
  return y + bandH + 3;
}

// ── AP Aging PDF ─────────────────────────────────────────────────────────────

export interface APAgingRowPDF {
  supplierName: string;
  invoiceNumber: string;
  poNumber: string | null;
  invoiceDate: string;
  dueDate: string;
  totalAmount: number;
  totalPaid: number;
  balance: number;
  daysOverdue: number;
  bucket: string;
  status: string;
}

export interface AgingSummaryPDF {
  current: number;
  days1_30: number;
  days31_60: number;
  days61_90: number;
  days90plus: number;
  totalOutstanding: number;
}

export function generateAPAgingPDF(rows: APAgingRowPDF[], summary: AgingSummaryPDF, filterDesc: string): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "AP Aging Report", filterDesc || "Accounts Payable Outstanding");

  y = drawSummaryBand(doc, [
    { label: "Total Outstanding", value: summary.totalOutstanding, color: C.red },
    { label: "Current", value: summary.current, color: C.green },
    { label: "1\u201330 Days", value: summary.days1_30, color: C.amber },
    { label: "31\u201360 Days", value: summary.days31_60, color: C.amber },
    { label: "61\u201390 Days", value: summary.days61_90, color: C.red },
    { label: "90+ Days", value: summary.days90plus, color: C.red },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Supplier", width: 40 },
    { header: "Invoice #", width: 27 },
    { header: "PO #", width: 23 },
    { header: "Invoice Date", width: 23 },
    { header: "Due Date", width: 22 },
    { header: "Total", width: 26, align: "right" },
    { header: "Paid", width: 25, align: "right" },
    { header: "Balance", width: 26, align: "right" },
    { header: "Days", width: 14, align: "right" },
    { header: "Bucket", width: 17, align: "center" },
    { header: "Status", width: 14, align: "center" },
  ];

  const tableRows = rows.map(r => [
    r.supplierName,
    r.invoiceNumber,
    r.poNumber ?? "\u2014",
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "",
    fmtINR(r.totalAmount),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
    r.bucket,
    r.status,
  ]);

  drawTable(doc, cols, tableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── AR Aging PDF ─────────────────────────────────────────────────────────────

export interface ARAgingRowPDF {
  customerName: string;
  customerType: string;
  customerGSTIN: string | null;
  invoiceNumber: string;
  invoiceDate: string;
  dueDate: string | null;
  grandTotal: number;
  totalPaid: number;
  balance: number;
  daysOverdue: number;
  bucket: string;
  status: string;
}

export function generateARAgingPDF(rows: ARAgingRowPDF[], summary: AgingSummaryPDF, filterDesc: string): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "AR Aging Report", filterDesc || "Accounts Receivable Outstanding");

  y = drawSummaryBand(doc, [
    { label: "Total Outstanding", value: summary.totalOutstanding, color: C.red },
    { label: "Current", value: summary.current, color: C.green },
    { label: "1\u201330 Days", value: summary.days1_30, color: C.amber },
    { label: "31\u201360 Days", value: summary.days31_60, color: C.amber },
    { label: "61\u201390 Days", value: summary.days61_90, color: C.red },
    { label: "90+ Days", value: summary.days90plus, color: C.red },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Customer", width: 36 },
    { header: "Type", width: 13, align: "center" },
    { header: "GSTIN", width: 28 },
    { header: "Invoice #", width: 26 },
    { header: "Invoice Date", width: 22 },
    { header: "Due Date", width: 22 },
    { header: "Grand Total", width: 26, align: "right" },
    { header: "Paid", width: 24, align: "right" },
    { header: "Balance", width: 25, align: "right" },
    { header: "Days", width: 13, align: "right" },
    { header: "Bucket", width: 17, align: "center" },
    { header: "Status", width: 15, align: "center" },
  ];

  const tableRows = rows.map(r => [
    r.customerName,
    r.customerType ?? "\u2014",
    r.customerGSTIN ?? "\u2014",
    r.invoiceNumber,
    r.invoiceDate?.slice(0, 10) ?? "",
    r.dueDate?.slice(0, 10) ?? "\u2014",
    fmtINR(r.grandTotal),
    fmtINR(r.totalPaid),
    fmtINR(r.balance),
    r.daysOverdue > 0 ? String(r.daysOverdue) : "Current",
    r.bucket,
    r.status,
  ]);

  drawTable(doc, cols, tableRows, y + 2);
  addPageFooter(doc);
  return doc.output("blob");
}

// ── Daily Pricing PDF ─────────────────────────────────────────────────────────

export interface PricingProductPDF {
  productName: string;
  sku: string;
  category: string;
  totalStock: number;
  unit: string;
  blendedCost: number | null;
  globalFloor: number | null;
  strictFloor: number | null;
  confirmedPrice: number;
  marginPct: number | null;
  minMarginPct: number;
  pressureLevel: string;
  source: "today" | "fallback" | "none";
  hasConfirmedToday: boolean;
  hasUnconfirmedSheet: boolean;
  hasConfirmedSheet: boolean;
  sellPriority: boolean;
}

export interface PortfolioPDF {
  totalInventoryCost: number;
  revenueAtConfirmedPrices: number;
  requiredRevenueAtMinMargin: number;
  portfolioMarginPct: number | null;
  portfolioStatus: "SAFE" | "AT RISK";
  productsAtRisk: number;
  productsWithoutPriceCount: number;
  productsSellPriority: number;
}

export function generatePricingPDF(products: PricingProductPDF[], portfolio: PortfolioPDF, filterDesc: string): Blob {
  const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
  let y = drawHeader(doc, "Daily Pricing Report", filterDesc || "FIFO Pricing & Margin Summary");

  y = drawSummaryBand(doc, [
    { label: "Inventory Cost", value: portfolio.totalInventoryCost, color: C.textPrimary },
    { label: "Revenue @ Conf. Prices", value: portfolio.revenueAtConfirmedPrices, color: C.green },
    { label: "Required @ Min Margin", value: portfolio.requiredRevenueAtMinMargin, color: C.amber },
  ], y + 2);

  const cols: ColDef[] = [
    { header: "Product", width: 40 },
    { header: "SKU", width: 22 },
    { header: "Category", width: 24 },
    { header: "Stock", width: 18, align: "right" },
    { header: "Blended Cost", width: 25, align: "right" },
    { header: "Global Floor", width: 25, align: "right" },
    { header: "Strict Floor", width: 25, align: "right" },
    { header: "Eff. Price", width: 25, align: "right" },
    { header: "Margin %", width: 18, align: "right" },
    { header: "Risk", width: 18, align: "center" },
    { header: "Source", width: 18, align: "center" },
    { header: "Status", width: 19, align: "center" },
  ];

  const tableRows = products.map(p => [
    (p.sellPriority ? "\uD83D\uDD25 " : "") + p.productName,
    p.sku,
    p.category,
    `${p.totalStock.toLocaleString()} ${p.unit}`,
    p.blendedCost !== null ? fmtINR(p.blendedCost) : "\u2014",
    p.globalFloor !== null ? fmtINR(p.globalFloor) : "\u2014",
    p.strictFloor !== null ? fmtINR(p.strictFloor) : "\u2014",
    fmtINR(p.confirmedPrice),
    p.marginPct !== null ? `${p.marginPct.toFixed(1)}%` : "\u2014",
    p.pressureLevel,
    p.source === "today" ? "Today" : p.source === "fallback" ? "Fallback" : "No Price",
    p.hasConfirmedToday ? "Confirmed" : p.hasUnconfirmedSheet ? "Pending" : "No Sheet",
  ]);

  drawTable(doc, cols, tableRows, y + 2, (i, row) => {
    const pressure = products[i]?.pressureLevel;
    if (pressure === "High Risk") return [255, 245, 245] as [number, number, number];
    return null;
  });

  addPageFooter(doc);
  return doc.output("blob");
}
